### ISSUE TITLE
Mutliple game crashes

### ISSUE THREAD

**Issue by Athrizel** [Thutmose/Thut#124]
## So my minecraft crashed in two different ways

Here's the first one

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 10/7/18 1:02 PM
Description: Unexpected error

java.lang.NoSuchMethodError: thut.lib.CompatWrapper.getStackSize(Lnet/minecraft/item/ItemStack;)I
	at thut.tech.common.items.ItemLinker.onItemUse(ItemLinker.java:348)
	at thut.tech.common.items.ItemLinker.func_180614_a(ItemLinker.java:303)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thut.tech.common.items.ItemLinker.onItemUse(ItemLinker.java:348)
	at thut.tech.common.items.ItemLinker.func_180614_a(ItemLinker.java:303)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Athrizel'/250, l='MpServer', x=-7774.67, y=126.00, z=-4338.78]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (248,64,244), Chunk: (at 8,4,4 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1895814 game time, 257629 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [GCEntityClientPlayerMP['Athrizel'/250, l='MpServer', x=-7774.67, y=126.00, z=-4338.78], EntityNeptuneLander['Space Lander'/283, l='MpServer', x=-7882.50, y=92.00, z=-4427.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1262495824 bytes (1204 MB) / 3050831872 bytes (2909 MB) up to 3050831872 bytes (2909 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m
	IntCache: cache: 0, tcache: 82, allocated: 1, tallocated: 10
	FML: MCP 9.42 Powered by Forge 14.23.3.2679 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version           | Source                                           | Signature                                |
	|:--------- |:------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2            | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | mcp                 | 9.42              | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.3.2679-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.3.2679      | forge-1.12.2-14.23.3.2679-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |                   | minecraft.jar                                    | None                                     |
	| UCHIJAAAA | actuallyadditions   | 1.12.2-r135       | ActuallyAdditions-1.12.2-r135.jar                | None                                     |
	| UCHIJAAAA | psi                 | r1.1-59           | Psi-r1.1-59.jar                                  | None                                     |
	| UCHIJAAAA | autoreglib          | 1.3-17            | AutoRegLib-1.3-17.jar                            | None                                     |
	| UCHIJAAAA | codechickenlib      | 3.1.8.341         | CodeChickenLib-1.12.2-3.1.8.341-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | avaritia            | 3.2.0             | Avaritia-1.12-3.2.0.13-universal.jar             | None                                     |
	| UCHIJAAAA | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCHIJAAAA | biomesoplenty       | 7.0.1.2384        | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar    | None                                     |
	| UCHIJAAAA | botania             | r1.10-354         | Botania r1.10-354.jar                            | None                                     |
	| UCHIJAAAA | redstoneflux        | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore        | 2.4.2             | BrandonsCore-1.12-2.4.2.157-universal.jar        | None                                     |
	| UCHIJAAAA | cofhcore            | 4.4.1             | CoFHCore-1.12.2-4.4.1.12-universal.jar           | None                                     |
	| UCHIJAAAA | draconicevolution   | 2.3.11            | Draconic-Evolution-1.12-2.3.11.290-universal.jar | None                                     |
	| UCHIJAAAA | mantle              | 1.12-1.3.2.24     | Mantle-1.12-1.3.2.24.jar                         | None                                     |
	| UCHIJAAAA | jei                 | 4.11.0.212        | jei_1.12.2-4.11.0.212.jar                        | None                                     |
	| UCHIJAAAA | tconstruct          | 1.12.2-2.9.1.65   | TConstruct-1.12.2-2.9.1.65.jar                   | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.181         | GalacticraftCore-1.12.2-4.0.1.181.jar            | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.181         | Galacticraft-Planets-1.12.2-4.0.1.181.jar        | None                                     |
	| UCHIJAAAA | mjrlegendslib       | 1.12.2-1.1.5      | MJRLegendsLib-1.12.2-1.1.5.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | extraplanets        | 1.12.2-0.4.3      | ExtraPlanets-1.12.2-0.4.3.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | mcjtylib_ng         | 2.6.7             | mcjtylib-1.12-2.6.7.jar                          | None                                     |
	| UCHIJAAAA | mekanism            | 1.12.2-9.4.10.345 | Mekanism-1.12.2-9.4.10.345.jar                   | None                                     |
	| UCHIJAAAA | moartinkers         | 0.5.4             | moartinkers-0.5.4.jar                            | None                                     |
	| UCHIJAAAA | moreplayermodels    | 1.12.2            | MorePlayerModels_1.12.2(18jan18).jar             | None                                     |
	| UCHIJAAAA | twilightforest      | 3.7.424           | twilightforest-1.12.2-3.7.424-universal.jar      | None                                     |
	| UCHIJAAAA | plustic             | 6.5.2.0           | plustic-6.5.2.0.jar                              | None                                     |
	| UCHIJAAAA | redstonearsenal     | 2.4.2             | RedstoneArsenal-1.12.2-2.4.2.9-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thutcore            | 5.19.8            | thutcore-1.12.2-5.19.8.jar                       | None                                     |
	| UCHIJAAAA | thutcore_compat     | 1.0               | thutcore-1.12.2-5.19.8.jar                       | None                                     |
	| UCHIJAAAA | thuttech            | 6.0.16            | thuttech-1.12.2-6.0.16.jar                       | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.07' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.07, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz

Here's the second one

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 10/7/18 1:16 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;)V
	at thut.tech.common.handlers.BlockHandler.registerBlocks(BlockHandler.java:61)
	at thut.tech.common.TechCore.registerBlocks(TechCore.java:171)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_155_TechCore_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thut.tech.common.handlers.BlockHandler.registerBlocks(BlockHandler.java:61)
	at thut.tech.common.TechCore.registerBlocks(TechCore.java:171)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_155_TechCore_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2500534720 bytes (2384 MB) / 3083337728 bytes (2940 MB) up to 3083337728 bytes (2940 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2679 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                           | Signature                                |
	|:----- |:------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2            | minecraft.jar                                    | None                                     |
	| UCH   | mcp                 | 9.42              | minecraft.jar                                    | None                                     |
	| UCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.3.2679-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.3.2679      | forge-1.12.2-14.23.3.2679-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore       |                   | minecraft.jar                                    | None                                     |
	| UCH   | actuallyadditions   | 1.12.2-r135       | ActuallyAdditions-1.12.2-r135.jar                | None                                     |
	| UCH   | psi                 | r1.1-59           | Psi-r1.1-59.jar                                  | None                                     |
	| UCH   | autoreglib          | 1.3-17            | AutoRegLib-1.3-17.jar                            | None                                     |
	| UCH   | codechickenlib      | 3.1.8.341         | CodeChickenLib-1.12.2-3.1.8.341-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | avaritia            | 3.2.0             | Avaritia-1.12-3.2.0.13-universal.jar             | None                                     |
	| UCH   | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                           | None                                     |
	| UCH   | biomesoplenty       | 7.0.1.2384        | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar    | None                                     |
	| UCH   | botania             | r1.10-354         | Botania r1.10-354.jar                            | None                                     |
	| UCH   | redstoneflux        | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | brandonscore        | 2.4.2             | BrandonsCore-1.12-2.4.2.157-universal.jar        | None                                     |
	| UCH   | cofhcore            | 4.4.1             | CoFHCore-1.12.2-4.4.1.12-universal.jar           | None                                     |
	| UCH   | draconicevolution   | 2.3.11            | Draconic-Evolution-1.12-2.3.11.290-universal.jar | None                                     |
	| UCH   | mantle              | 1.12-1.3.2.24     | Mantle-1.12-1.3.2.24.jar                         | None                                     |
	| UCH   | jei                 | 4.11.0.212        | jei_1.12.2-4.11.0.212.jar                        | None                                     |
	| UCH   | tconstruct          | 1.12.2-2.9.1.65   | TConstruct-1.12.2-2.9.1.65.jar                   | None                                     |
	| UCH   | galacticraftcore    | 4.0.1.181         | GalacticraftCore-1.12.2-4.0.1.181.jar            | None                                     |
	| UCH   | galacticraftplanets | 4.0.1.181         | Galacticraft-Planets-1.12.2-4.0.1.181.jar        | None                                     |
	| UCH   | mjrlegendslib       | 1.12.2-1.1.5      | MJRLegendsLib-1.12.2-1.1.5.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | extraplanets        | 1.12.2-0.4.3      | ExtraPlanets-1.12.2-0.4.3.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | mcjtylib_ng         | 2.6.7             | mcjtylib-1.12-2.6.7.jar                          | None                                     |
	| UCH   | mekanism            | 1.12.2-9.4.10.345 | Mekanism-1.12.2-9.4.10.345.jar                   | None                                     |
	| UCH   | moartinkers         | 0.5.4             | moartinkers-0.5.4.jar                            | None                                     |
	| UCH   | moreplayermodels    | 1.12.2            | MorePlayerModels_1.12.2(18jan18).jar             | None                                     |
	| UCH   | twilightforest      | 3.7.424           | twilightforest-1.12.2-3.7.424-universal.jar      | None                                     |
	| UCH   | plustic             | 6.5.2.0           | plustic-6.5.2.0.jar                              | None                                     |
	| UCH   | redstonearsenal     | 2.4.2             | RedstoneArsenal-1.12.2-2.4.2.9-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thutcore            | 5.19.8            | thutcore-1.12.2-5.19.8.jar                       | None                                     |
	| UCH   | thutcore_compat     | 1.0               | thutcore-1.12.2-5.19.8.jar                       | None                                     |
	| UCH   | thuttech            | 6.1.5             | thuttech-1.12.2-6.1.5.jar                        | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.07' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.07, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz

#### Issue Description:
Two different crashes caused by different things

#### What happens:
So the first instance was with an older version of the elevators mod. The crash occurs when I try to create an elevator, I can right click to set point A but as soon as I shift right click to set point B it crashes. It doesn't matter if I make the elevator with vanilla or modded blocks, it still crashes.

The second instance comes from me trying to update the elevators mod to the most recent version and then try to load up minecraft, which crashes as soon as the mods initialize in the loading process. The only distinction I noticed between these was that the old version that loaded with minecraft said "Thuttech" in the mod list, while the most recent versions have the full name in the mod list instead of just "Thuttech"

#### What you expected to happen:
I certainly didn't expect it to crash

#### Steps to reproduce:

1. Use thuttech-1.12.2-6.0.16
2. Load the game
3. Try to make an elevator
-------------------------------------------------------------------------------------------------------------------
1. Put thuttech-1.12.2-6.1.5 in mods
2. Try to load Minecraft
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.
Here's a list of every mod I've been using alongside thuttech

- thutcore-1.12.2-5.19.8
- thuttech-1.12.2-6.1.5
- thuttech-1.12.2-6.0.16
- ActuallyAdditions-1.12.2-r135
- AutoRegLib-1.3-17
- Avaritia-1.12-3.2.0.13-universal
- Baubles-1.12-1.5.2
- BiomesOPlenty-1.12.2-7.0.1.2384-universal
- Botania r1.10-354
- BrandonsCore-1.12-2.42.157-universal
- CodeChickenLib-1.12.2-3.1.8.341-universal
- CoFHCore-1.12.2-4.4.1.12-universal
- Draconic-Evolution-1.12-2.3.11.290-universal
- ExtraPlanets-1.12.2-0.4.3
- GalacticraftCore-1.12.2-4.0.1.181
- Galacticraft-Planets-1.12.2-4.0.1.181
- jei_1.12.2-4.11.0.212
- Mantle-1.12-1.3.2.24
- mcjtylib-1.12-2.6.7
- Mekanism-1.12.2-9.4.10.345
- MicdoodleCore-1.12.2-4.0.1.181
- MJRLegendsLib-1.12.2-1.1.5
- moartinkers-0.5.4
- MorePlayerModels_1.12.2(18jan18)
- plustic-6.5.2.0
- Psi-r1.1-59
- RedstoneArsenal-1.12.2-2.4.2.9-universal
- RedstoneFlux-1.12-2.0.1.2-universal
- TConstruct-1.12.2-2.9.1.65
- twilightforest-1.12.2-3.7.424-universal
- Minecraft: 1.12.2
- Forge: 14.23.3.2679

**Comment by Thutmose** [comment]
First crash is caused by your version of thutcore being too far ahead of your version of the elevators mod.

Second crash is caused by your version of forge being outdated.

Fix for both crashes: Update your mods.
