### ISSUE TITLE
Error using Thut's Elevators in 1.15.2 server

### ISSUE THREAD

**Issue by DarkenLM** [Thutmose/Thut#167]
#### Issue Description:
Can't use Thut's elevators v1.15.2-8.0.2 mod in 1.15.2 servers.

#### What happens:
When I start the server, it gives me this error:
```
[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Thut Crafts (thutcrafts) has failed to load correctly
§7net/minecraftforge/fml/config/ModConfig$ConfigReloading,
        Thut Elevators (thuttech) has failed to load correctly
§7net/minecraftforge/fml/config/ModConfig$ConfigReloading,
        Thut Core (thutcore) has failed to load correctly
§7net/minecraftforge/fml/config/ModConfig$ConfigReloading
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}
�[m�[1;31m[17:11:47] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Utilizador\Desktop\Minecraft\Server\Server 1.15.2 forge\.\crash-reports\crash-2020-03-13_17.11.47-server.txt
�[m�[32m[17:11:47] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
�[m�[32m[17:11:47] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
�[m�[1;31m[17:11:47] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:185) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:549) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:676) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}
```

Crash report:
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 13-03-2020 17:11
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Thut Crafts (thutcrafts) has failed to load correctly
ยง7net/minecraftforge/fml/config/ModConfig$ConfigReloading,
	Thut Elevators (thuttech) has failed to load correctly
ยง7net/minecraftforge/fml/config/ModConfig$ConfigReloading,
	Thut Core (thutcore) has failed to load correctly
ยง7net/minecraftforge/fml/config/ModConfig$ConfigReloading
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1592097464 bytes (1518 MB) / 2082471936 bytes (1986 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xmx4G -Xms1G
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.18-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		backpacked-1.4.1-mc1.15.2.jar Backpacked {backpacked@1.4.1 CREATE_REGISTRIES}
		XL-Food-Mod-1.15.2.jar XL Food Mod {xlfoodmod@2.2.2 CREATE_REGISTRIES}
		obfuscate-0.3.4-1.15.2.jar Obfuscate {obfuscate@0.3.4 CREATE_REGISTRIES}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 CREATE_REGISTRIES}
		thuttech-1.15.2-8.0.2.jar Thut Elevators {thuttech@8.0.2 ERROR}
		thutcore-1.14.4-6.0.2.jar Thut Core {thutcore@6.0.2 ERROR, thutcrafts@6.0.2 ERROR}
		MrCrayfishs-Furniture-Mod-1.15.2.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 CREATE_REGISTRIES}
		Cyclic-1.15.2-0.1.10.jar Cyclic {cyclic@1.15.2-0.1.10 CREATE_REGISTRIES}
		[1.15.2]+SecurityCraft+v1.8.17.jar SecurityCraft {securitycraft@v1.8.17 CREATE_REGISTRIES}
		vehicle-0.42.6-mc1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.42.6 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```
#### What you expected to happen:
I expected the mod to correctly load.

#### Steps to reproduce:

1. Download and install forge forge-1.15.2-31.1.18 (server side)
2. Download and put in the mods folder of the server the mod **thuttech-1.15.2-8.0.2**
3. Download and put in the mods folder of the server the mod **thutcore-1.15.2-7.0.2**
4. Run the server
____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutcore: 1.15.2-7.0.2
- Minecraft: 1.15.2
- Forge: 1.15.2-31.1.18

**Comment by Thutmose** [comment]
I will look into this, it seems like it might be an issue with the thutcore version currently released, as it is working in my testing server (which uses the version of thutcore packed in pokecube)

**Comment by Thutmose** [comment]
If this issue still occurs for 1.15.2, please re-make in https://github.com/Thuts-Mods/ThutTech/issues
