### ISSUE TITLE
[Minecraft 1.11] thutcore-4.0.1.b.jar crash report

### ISSUE THREAD

**Issue by YswMusician** [Thutmose/Thut#27]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.1-1.11.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.0.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 11/17/16 7:44 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ThutCore (thutcore)
Caused by: java.lang.NoClassDefFoundError: thut/core/common/blocks/tileentity/TileEntityMultiBlockPart
	at thut.core.common.CommonProxy.registerTEs(CommonProxy.java:73)
	at thut.core.common.ThutCore.load(ThutCore.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: thut.core.common.blocks.tileentity.TileEntityMultiBlockPart
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 955078608 bytes (910 MB) / 1476395008 bytes (1408 MB) up to 9535225856 bytes (9093 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10230m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.0.2138 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.0.2138.jar) 
	UCHI	forge{13.19.0.2138} [Minecraft Forge] (forge-1.11-13.19.0.2138.jar) 
	UCHI	BetterAchievements{0.4.0.36} [Better Achievements] (BetterAchievements-1.11-0.4.0.36.jar) 
	UCHI	betteragriculture{1.0} [Better Agriculture] (BetterAgriculture-1.11-1.0.jar) 
	UCHI	bettertitlescreen{1.3} [Better Title Screen] (BetterTitleScreen-1.11-1.3.jar) 
	UCHI	biomesoplenty{6.0.0.2099} [Biomes O' Plenty] (BiomesOPlenty-1.11-6.0.0.2099-universal.jar) 
	UCHI	shetiphiancore{3.4.0} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.0.jar) 
	UCHI	endertanks{1.5.0} [EnderTanks] (endertanks-1.11.0-1.5.0.jar) 
	UCHI	hammerz{1.11-0.1.4.19} [Hammerz] (hammerz-1.11-0.1.4.19.jar) 
	UCHI	reborncore{2.9.0.4} [RebornCore] (RebornCore-1.11-2.9.0.4-universal.jar) 
	UCHI	hardcoremapreset{2.5.0.1} [HardcoreMapReset] (HardCoreMapReset-2.5.0.1.jar) 
	UCHI	harvest{1.11-1.2.0-12} [Harvest] (Harvest-1.11-1.2.0-12.jar) 
	UCHI	jei{4.0.1.190} [Just Enough Items] (jei_1.11-4.0.1.190.jar) 
	UCHI	jeresources{0.6.0.90} [Just Enough Resources] (JustEnoughResources-1.11-0.6.0.90.jar) 
	UCHI	kleeslabs{4.3.1} [KleeSlabs] (KleeSlabs_1.11-4.3.1.jar) 
	UCHI	llibrary{1.7.1} [LLibrary] (llibrary-1.7.1-1.11.jar) 
	UCHI	login_shield{1.11-1-g16fc261} [Login Shield] (Login_Shield-1.11-1-g16fc261.jar) 
	UCHI	mercurius{1.0.1} [Mercurius] (Mercurius-1.11-1.0.1.jar) 
	UCHI	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.11-4.3.1.jar) 
	UCHI	oreexcavation{1.3.37} [OreExcavation] (OreExcavation-1.3.37.jar) 
	UCHI	ping{1.3.0} [Ping] (Ping-1.11-1.3.0.jar) 
	UCHI	reborncore-mcmultipart{2.9.0.4} [reborncore-MCMultiPart] (RebornCore-1.11-2.9.0.4-universal.jar) 
	UCHI	thedragonlib{1.11-2.0.0} [TheDragonLib] (thedragonlib-1.11-2.0.0.jar) 
	UCHI	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.11-1.3.3.jar) 
	UCHE	thutcore{4.0.1} [ThutCore] (thutcore-4.0.1.b.jar) 
	UCHI	underphangables{1.0.3} [Underp Hangables] (underphangables-1.11.0-1.0.3.jar) 
	UCHI	WIT{1.0.21} [WIT] (WIT-1.11-1.0.21-40.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.1-1.11.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.0.jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.86' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'

**Comment by Thutmose** [comment]
oops, I must have messed up when I compiled b, b was supposed to fix this. will recompile now.

**Comment by Thutmose** [comment]
Uploaded 4.0.1.c which fixes this issue, it should be at this link shortly: https://minecraft.curseforge.com/projects/thutcore/files/2345822
