### ISSUE TITLE
Pokecube issue

### ISSUE THREAD

**Issue by matthewsflower** [Thutmose/Thut#31]
Tried to install the Pokecube mod to 1.11 which when installed by itself states that it requires Thutcore.
When I install Thutcore it then doesn't even load the game I get:

---- Minecraft Crash Report ----
// You're mean.

Time: 12/11/16 6:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Pokécube Revival (pokecube_adventures)
Caused by: java.lang.NoClassDefFoundError: pokecube/adventures/blocks/cloner/block/BlockCloner
	at pokecube.adventures.handlers.BlockHandler.registerBlocks(BlockHandler.java:36)
	at pokecube.adventures.PokecubeAdv.preInit(PokecubeAdv.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:263)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: pokecube.adventures.blocks.cloner.block.BlockCloner
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: thut/core/common/blocks/BlockRotatable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: thut.core.common.blocks.BlockRotatable
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 189683456 bytes (180 MB) / 376188928 bytes (358 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.0.2141 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.0.2141.jar) 
	UCH	forge{13.19.0.2141} [Minecraft Forge] (forge-1.11-13.19.0.2141.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCH	thutcore{4.0.1} [ThutCore] (thutcore-4.0.1.k.jar) 
	UCH	pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-5.0.0.a.jar) 
	UCH	pokecube{5.0.0} [Pokécube Core] (Pokecube Core-5.0.0.a.jar) 
	UCH	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-5.0.0.a.jar) 
	UCH	pokecube_mobs{2.3.6} [Pokécube Mobs] (Pokecube Mobs-2.3.6.jar) 
	UCH	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.3.6.jar) 
	UCE	pokecube_adventures{5.0.0} [Pokécube Revival] (Pokecube Revival-5.0.0_rc1.jar) 
	UCH	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-5.0.0_rc1.jar) 
	UCH	pokeplayer{@VERSION} [Pokecube Mystery Dungeon] (Pokecube Revival-5.0.0_rc1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce GT 240/PCIe/SSE2'

**Comment by Thutmose** [comment]
I suggest updating your mods, they are mostly old versions, this particular issue is caused by using an older version of ThutCore with a newer version of Revival.

**Comment by matthewsflower** [comment]
But with the latest version I still get this:
---- Minecraft Crash Report ----
// Don't do that.

Time: 12/11/16 9:21 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Pokécube Core (pokecube)
Caused by: java.lang.ExceptionInInitializerError
	at pokecube.core.database.PokedexEntry$EvolutionData.<init>(PokedexEntry.java:86)
	at pokecube.core.database.PokedexEntry$EvolutionData.<init>(PokedexEntry.java:104)
	at pokecube.core.database.PokedexEntryLoader.parseEvols(PokedexEntryLoader.java:735)
	at pokecube.core.database.PokedexEntryLoader.preCheckEvolutions(PokedexEntryLoader.java:1123)
	at pokecube.core.database.PokedexEntryLoader.makeEntries(PokedexEntryLoader.java:681)
	at pokecube.core.database.Database.init(Database.java:392)
	at pokecube.core.PokecubeCore.preInit(PokecubeCore.java:471)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:263)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:438)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: byName
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:123)
	at thut.lib.CompatWrapper.<clinit>(CompatWrapper.java:180)
	... 43 more
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: byName
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:96)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:119)
	... 44 more
Caused by: java.lang.NoSuchFieldException: byName
	at java.lang.Class.getDeclaredField(Class.java:2062)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:87)
	... 45 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 163194624 bytes (155 MB) / 373755904 bytes (356 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.0.2141 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.0.2141.jar) 
	UCH	forge{13.19.0.2141} [Minecraft Forge] (forge-1.11-13.19.0.2141.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCH	thutcore{4.3.1} [ThutCore] (thutcore-4.3.1.jar) 
	UCH	pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-5.0.0.a.jar) 
	UCE	pokecube{5.0.0} [Pokécube Core] (Pokecube Core-5.0.0.a.jar) 
	UCH	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-5.0.0.a.jar) 
	UCE	pokecube_mobs{2.3.6} [Pokécube Mobs] (Pokecube Mobs-2.3.6.jar) 
	UCH	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.3.6.jar) 
	UCE	pokecube_adventures{5.0.0} [Pokécube Revival] (Pokecube Revival-5.0.0_rc1.jar) 
	UCH	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-5.0.0_rc1.jar) 
	UCE	pokeplayer{@VERSION} [Pokecube Mystery Dungeon] (Pokecube Revival-5.0.0_rc1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce GT 240/PCIe/SSE2'

**Comment by Thutmose** [comment]
That still isn't latest versions of Pokecube Core, Pokecube Revival and Pokecube Mobs, or Minecraft Forge.
